### ISSUE TITLE
Spaces not correctly handled when creating config file

### ISSUE THREAD

**Issue by kyleawayan** [mattduffy/exiftool#10]
Here are the lines where I think may have caused this:

https://github.com/mattduffy/exiftool/blob/efe08cbc00a72a5671af5386c76a57ad9f82f30a/src/index.js#L333-L334

I was using https://github.com/ToTheMax/Snapchat-All-Memories-Downloader which has your library in it, but then ran into a issue where the config file actually went outside of the project's folder. I do not know the exact reason why, but the main issue here is when I curiously opened the file, the file path was missing the first word of my project folder.

E.g. my folder was named "SNAPCHAT MEMORIES", but then the file contained:
```
'XMP:LocationCreatedGPSLongitude', 'XMP:LocationShownGPSLatitude', 'XMP:LocationShownGPSLongitude'],
  StripGPS => ['gps:all='],
 MEMORIES/Snapchat-All-Memories-Downloader/node_modules/@mattduffy/exiftool/src/exiftool.config
 ```
 
 which only had "MEMORIES" in the path.

**Comment by mattduffy** [comment]
You are correct, spaces in file paths were causing problems.  That condition was neglected in the test suite.  Thanks for catching that and submitting this github issue.

I have updated the package to correct this problem.  

Since you are using @mattduffy/exiftool as a dependency of another project, you can either try to manually update @mattduffy/exiftool to latest (version 1.13.3) or, if you want, you can apply the linked patch file.

[quote-spaces.patch](https://github.com/user-attachments/files/16120984/quote-spaces.patch)

Assuming you save the attached patch file to your local desktop, patching would look something like this:
```bash
cd <path-your-node-project>/node_modules/@mattduffy/exiftool/src
patch -u -b index.js -i ~/Desktop/quote-spaces.patch
```

**Comment by kyleawayan** [comment]
Thank you very much!
