### ISSUE TITLE
Doesn't pass config when writing metadata

### ISSUE THREAD

**Issue by crawft** [mattduffy/exiftool#8]
I'm trying to write custom tags specified in exiftool.config and have figured out it fails because the -config option isn't being passed to exiftool, if I do that manually on the command line, it works.

**Comment by mattduffy** [comment]
Hi.  Thanks for the feedback.  Can you please provide a copy of the exiftool command that is included in the return object of the ``writeMetadata()`` method?  In general, with this package, writing new data to tags doesn't require the ``-config exiftool.config`` argument.  Are you trying to save a new shortcut to the config file, and then use that shortcut in the ``writeMetadata()`` method?

**Comment by mattduffy** [comment]
I have published a patch update to the package which includes the -config <path/to/exiftool.config> argument in the command to write metadata.  The new version of the package is v1.7.1 on npm.com.  Let me know if this solves your problem.  Getting shortcuts to write new values to tags can be a bit complicated and isn't fully supported in this package yet because there are LOTS of edge cases that tricky.  But if all you needed was the -config argument to be included, maybe this will work for you.

**Comment by crawft** [comment]
Sorry to miss your somments, the command being generated was:

`/opt/homebrew/bin/exiftool -XMP-SA:Latitude=37.812440528660765 /Users/crawford/NewNow/Spelfie/API/tech/GeoTIFF/img/maxar/103001005C2E5E00-visual_SA.webp'`

which failed but if I run this on the command line, it works

`exiftool -config /Users/crawford/NewNow/Spelfie/API/tech/GeoTIFF/exiftool.config -XMP-SA:Latitude=37.812440528660765 /Users/crawford/NewNow/Spelfie/API/tech/GeoTIFF/img/maxar/103001005C2E5E00-visual_SA.webp`

I've updated the package and can confirm it now works, thanks!
